---
- name: "Install Prerequisites."
  apt:
    name: "{{ mysql_prerequisites }}"
    state: present
    update_cache: 'yes'

- name: "Install MySQL Server."
  apt:
    name: "{{ mysql_server_package }}"
    state: present
    update_cache: 'yes'
