---
- name: "Install Prerequisites."
  package:
    name: "{{ mariadb_prerequisites }}"
    state: present

- name: "Install MariaDB Server."
  package:
    name: mariadb-server
    state: present

- name: "Start MariaDB Server."
  service:
    name: mariadb
    state: started
    enabled: 'true'
